In [1]:
import pandas as pd
file_path = r"C:/Users/RISHIKESH/Downloads/archive/globalterrorismdb_0718dist.csv"
df = pd.read_csv(file_path, encoding='latin1', low_memory=False)

In [2]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [3]:
print(df[["iyear", "latitude"]])

        iyear   latitude
0        1970  18.456792
1        1970  19.371887
2        1970  15.478598
3        1970  37.997490
4        1970  33.580412
...       ...        ...
181686   2017   2.359673
181687   2017  35.407278
181688   2017   6.900742
181689   2017  24.798346
181690   2017   7.209594

[181691 rows x 2 columns]

In [4]:
df[["iyear", "latitude"]] = scaler.fit_transform(df[["iyear", "latitude"]])

In [5]:
print(df[["iyear", "latitude"]])

        iyear  latitude
0         0.0  0.560392
1         0.0  0.567553
2         0.0  0.537086
3         0.0  0.713306
4         0.0  0.678741
...       ...       ...
181686    1.0  0.434424
181687    1.0  0.693037
181688    1.0  0.469960
181689    1.0  0.610017
181690    1.0  0.472377

[181691 rows x 2 columns]

In [6]:
numeric_columns = df.select_dtypes(include = "number").columns

In [8]:
df[numeric_columns].head()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,...,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,0.0,7,2,0,58,2,0.560392,-69.951164,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1,197000000002,0.0,0,0,0,130,1,0.567553,-99.086624,1.0,...,800000.0,NaN,NaN,NaN,NaN,NaN,0,1,1,1
2,197001000001,0.0,1,0,0,160,5,0.537086,120.599741,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1
3,197001000002,0.0,1,0,0,78,8,0.713306,23.762728,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1
4,197001000003,0.0,1,0,0,101,4,0.678741,130.396361,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1

In [9]:
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [10]:
df[numeric_columns].head()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,...,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,0.000000e+00,0.0,0.583333,0.064516,0.0,0.054,0.090909,0.560392,0.999997,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,0.9,0.9,0.9,0.9
1,2.122107e-10,0.0,0.000000,0.000000,0.0,0.126,0.000000,0.567553,0.999997,0.00,...,0.0008,NaN,NaN,NaN,NaN,NaN,0.9,1.0,1.0,1.0
2,2.122101e-04,0.0,0.083333,0.000000,0.0,0.156,0.363636,0.537086,0.999999,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0
3,2.122104e-04,0.0,0.083333,0.000000,0.0,0.074,0.636364,0.713306,0.999998,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0
4,2.122106e-04,0.0,0.083333,0.000000,0.0,0.097,0.272727,0.678741,0.999999,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0